apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        {{- if .Values.dapr.enabled }}
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ .Values.dapr.appId | quote }}
        dapr.io/app-port: {{ .Values.dapr.appPort | quote }}
        dapr.io/log-level: {{ .Values.dapr.logLevel | quote }}
        dapr.io/enable-api-logging: "true"
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet: { path: /healthz, port: {{ .Values.containerPort }} }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: {{ .Values.containerPort }} }
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml .Values.extraEnvFrom | nindent 12 }}
          {{- end }}